//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEETING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEETING()
        {
            this.MEMBERs = new HashSet<MEMBER>();
            this.TASKs = new HashSet<TASK>();
        }
    
        public string Create_by { get; set; }
        public string Meeting_name { get; set; }
        public Nullable<System.DateTime> Date_Start { get; set; }
        public Nullable<System.DateTime> Date_End { get; set; }
        public bool Meeting_Confirmed { get; set; }
        public int Category_id { get; set; }
        public int Meeting_id { get; set; }
        public string Lacation { get; set; }
        public string Status { get; set; }
        public string Meeting_report { get; set; }
        public string Create_by_name { get; set; }
        public Nullable<System.DateTime> Date_Create { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual ATTACHMENT ATTACHMENT { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEMBER> MEMBERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK> TASKs { get; set; }
    }
}
