//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTHER_ACCOUNT
    {
        public string othUser_id { get; set; }
        public string othUser_office { get; set; }
        public string othUser_Email { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
